//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortunesFormsUI.FortuneServiceWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FortuneServiceWcf.ICookieService")]
    public interface ICookieService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICookieService/GetCookie", ReplyAction="http://tempuri.org/ICookieService/GetCookieResponse")]
        string GetCookie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICookieService/GetCookie", ReplyAction="http://tempuri.org/ICookieService/GetCookieResponse")]
        System.Threading.Tasks.Task<string> GetCookieAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICookieServiceChannel : FortunesFormsUI.FortuneServiceWcf.ICookieService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CookieServiceClient : System.ServiceModel.ClientBase<FortunesFormsUI.FortuneServiceWcf.ICookieService>, FortunesFormsUI.FortuneServiceWcf.ICookieService {
        
        public CookieServiceClient() {
        }
        
        public CookieServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CookieServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CookieServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CookieServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCookie() {
            return base.Channel.GetCookie();
        }
        
        public System.Threading.Tasks.Task<string> GetCookieAsync() {
            return base.Channel.GetCookieAsync();
        }
    }
}
